name: my_manual_workflow

on:
  workflow_dispatch:

jobs:
  manual-worklow-test:
    runs-on: ubuntu-latest

    steps:
      - name: First step
        run: |
          echo "Cadana"
          echo "Torono"
  
