name: Multi-Build-stage-tsting

on:
  push:
    branches: [ "main" ]

jobs:
  first-workflow-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: |
          echo "First Step"
          echo "Hello, World"

  second-workflow-job-2:
    runs-on: ubuntu-latest
    needs: first-workflow-job-1
    steps:
      - name: Second step
        run: |
          echo "Second Step"
          echo "Hello, World"
